#!/usr/bin/env bash
# rvm after_install hook to provide selinux support
# This script will make sure the correct selinux contexts are set on ruby
# files after each ruby version install.

echo "Test hook executing"
env | grep -i rvm

if [ -x '/usr/sbin/semanage' -a -x '/sbin/restorecon' ]; then
  echo "executables good"
else
  echo "executables bad"
fi

exit

# Set up rvm file contexts if they are not already present
if ! semanage fcontext -l | /bin/grep -q rvm; then
  semanage fcontext -a -t bin_t '/usr/(local|lib)/rvm/wrappers(/.*)?'
  semanage fcontext -a -t bin_t '/usr/(local|lib)/rvm/rubies/ruby-.*/bin(/.*)?'
  semanage fcontext -a -t lib_t '/usr/(local|lib)/rvm/rubies/ruby-.*/lib(/.*)?'
  semanage fcontext -a -t lib_t '/usr/(local|lib)/rvm/gems(/.*)?'
  semanage fcontext -a -t passenger_exec_t '/usr/(local|lib)/rvm/gems/ruby-.*/gems/passenger-.*/agents(/.*)?'
fi
