#!/usr/bin/env bash
# rvm after_install hook to provide selinux support
# This script will make sure the correct selinux contexts are set on ruby
# files after each ruby version install.

if [ ! \( -x /usr/sbin/semanage -a -x /sbin/restorecon \) ]; then
  echo "SELinux executables missing, rvm after_install hook failed"
  exit
fi

# Set up rvm file context patterns if they are not already present
# This will handle installs in either /usr/local/rvm or /usr/lib/rvm
semanage fcontext -l | /bin/grep -q rvm; || {
  semanage fcontext -a -t bin_t '/usr/(local|lib)/rvm/wrappers(/.*)?'
  semanage fcontext -a -t bin_t '/usr/(local|lib)/rvm/rubies/ruby-.*/bin(/.*)?'
  semanage fcontext -a -t lib_t '/usr/(local|lib)/rvm/rubies/ruby-.*/lib(/.*)?'
  semanage fcontext -a -t lib_t '/usr/(local|lib)/rvm/gems(/.*)?'
  semanage fcontext -a -t passenger_exec_t '/usr/(local|lib)/rvm/gems/ruby-.*/gems/passenger-.*/agents(/.*)?'
}

# Run restorecon on the rvm hierarchy to fix the contexts
restorecon -R $rvm_path
